INSERT INTO TB_CUSTOMER_ACCOUNT(ID, AGENCY_CODE, DIGIT_VERIFICATION, NAME_OWNER, NUMBER_ACCOUNT, REGISTER_ID) 
VALUES(1, '25', '55', 'Maverick', '1234', '258');

INSERT INTO TB_CUSTOMER_ACCOUNT(ID, AGENCY_CODE, DIGIT_VERIFICATION, NAME_OWNER, NUMBER_ACCOUNT, REGISTER_ID) 
VALUES(2, '45', '2', 'Lua', '4321', '873');